### ISSUE TITLE
Client side event spam + Lead to nothing

### ISSUE THREAD

**Issue by Rubylium** [TheeDeer/deerAntiNPC#1]
On the client side script, line 13, the server event lead to ... No where ? I didn't see it registered anywhere on the server side script.

An other issue, the server event is sending an event for every ped that need to be deleted, that lead to a big event spam if there is lot of entity to delete, would be better to add all peds to delete into a table, then send the table on the server side to delete entities.

And last little issue, the event used to send entity on the server side send the entity id, not the net id. Entity id will lead to nothing on server side, you need to send the net id of the entity, then on the server side you get the entity id from the net id :)

![image](https://user-images.githubusercontent.com/19718604/110921850-4e8cb080-831f-11eb-8f8b-278a7ca2d2e9.png)

**Comment by TheeDeer** [comment]
Fixed in latest, sorry about that.
